<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAqoqdz3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAqoqdz3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAqoqdz3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAqoqdz3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAqoqdz3\appProdProjectContainer([
    'container.build_hash' => 'Aqoqdz3',
    'container.build_id' => '6d633340',
    'container.build_time' => 1610357701,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAqoqdz3');
