<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUpaexsb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUpaexsb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUpaexsb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUpaexsb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUpaexsb\appDevDebugProjectContainer([
    'container.build_hash' => 'Upaexsb',
    'container.build_id' => '48e2d6bb',
    'container.build_time' => 1610377229,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUpaexsb');
