-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : lun. 16 août 2021 à 07:05
-- Version du serveur :  5.7.31
-- Version de PHP : 7.4.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `edward`
--

-- --------------------------------------------------------

--
-- Structure de la table `comics`
--

DROP TABLE IF EXISTS `comics`;
CREATE TABLE IF NOT EXISTS `comics` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titre` varchar(150) NOT NULL,
  `heros` varchar(150) NOT NULL,
  `promotion` tinyint(1) NOT NULL,
  `dessinateur` varchar(150) NOT NULL,
  `date` varchar(100) NOT NULL,
  `isbn` decimal(65,0) DEFAULT NULL,
  `nouveaute` tinyint(1) NOT NULL,
  `categorie` varchar(150) NOT NULL,
  `scenariste` varchar(150) NOT NULL,
  `disponibilite` varchar(1) NOT NULL,
  `avis` int(11) DEFAULT NULL,
  `resume` varchar(1500) DEFAULT NULL,
  `nbrPages` int(11) NOT NULL,
  `photo` varchar(150) NOT NULL,
  `selection` tinyint(1) NOT NULL,
  `prix` float NOT NULL,
  `editeur` varchar(150) NOT NULL,
  `univers` varchar(150) DEFAULT NULL,
  `serie` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=41 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `comics`
--

INSERT INTO `comics` (`id`, `titre`, `heros`, `promotion`, `dessinateur`, `date`, `isbn`, `nouveaute`, `categorie`, `scenariste`, `disponibilite`, `avis`, `resume`, `nbrPages`, `photo`, `selection`, `prix`, `editeur`, `univers`, `serie`) VALUES
(1, 'Harleen', 'Harley Quinn', 0, 'Sejic Stjepan', '12/06/2020', '1026816068', 1, 'Super-vilains', 'Sejic Stjepan', '2', 5, 'Après des études mouvementées qui ont entamé sa confiance en elle, la jeune psychologue Harleen Quinzel pense enfin avoir décroché le poste de ses rêves en étant embauchée à l’Asile d’Arkham afin d’apporter son soutien et son expertise aux plus grands criminels de Gotham. Mais il est un être au sein de cet asile qui va à la fois faire chavirer son esprit et son cœur : le Joker ! Petit à petit, Harleen va se laisser séduire puis sombrer dans un abîme de folie y laissant à tout jamais son innocence et ses illusions perdues.', 224, 'assets/img/Harleen.png', 0, 20, 'Urban Comics', 'DC Comics', NULL),
(2, 'Batman: Joker War - Tome 1', 'Batman', 0, 'Jorge Jimenez', '09/02/2021', '9781779507907', 1, 'Super-vilains', 'James Tynion IV', '1', 5, 'This is it: the Clown Prince of Crime battles the Dark Knight Detective head-to-head for the last time. And one way or another, this explosive struggle will pave the way to the future of Gotham City! The Joker has never wanted to win before-he’s never wanted his battle with Batman to end-but now his motivation has shifted. As The Joker assembles an army, Batman reels from a debilitating Joker Toxin attack. Amid the chaos, the villains of Gotham City are waiting out the carnage Joker has unleashed-and Catwoman assembles an army of her own! Plus, Harley Quinn battles Punchline, and Clownhunter joins the action!', 100, 'assets/img/Batman_The_Joker_War.png', 0, 20, 'DC Comics', 'DC Comics', 'Joker War'),
(3, 'Wonder Woman - Tome 1', 'Wonder Woman', 0, 'Cary Nord', '08/06/2016', '9791026815792', 0, 'Super-girls', 'G. Willow Wilson', '1', 3, 'Wonder Woman survives her battle against young god Ares only to discover her mother is missing-and so is Aphrodite\'s child! Together, they\'ll turn the world upside down to find them, but they must fight a pack of wayward Titans first. Can they convince Diana\'s foe Giganta to join the fight?', 175, 'assets/img/wonderwoman1.png', 0, 22, 'DC Comics', 'DC Comics', 'Wonder Woman'),
(4, 'Marvel Knights: Spider-Man', 'Spiderman', 0, 'Terry Dodson', '15/02/2012', '1026816068', 0, 'Super-héros', 'Mark Millar', '1', 5, 'Piqué par une araignée radioactive lors d\'une expérience scientifique, Peter Parker acquiert d\'extraordinaires pouvoirs, force et agilité surhumaines, adhérence aux parois, et un sixième sens qui l\'alerte en cas de danger. La mort de son oncle Ben - tué par un cambrioleur que Peter a laissé filer quelques jours plus tôt - incite le jeune étudiant à se transformer en super-héros justicier.', 272, 'assets/img/spider-man-le-dernier-combat.png', 0, 35, 'Marvel', 'Marvel', 'Marvel Knights'),
(5, 'Wonder Woman - Tome 2', 'Wonder Woman', 0, 'Xermanico', '07/04/2020', '9791026815796', 0, 'Super-girls', 'Steve Orlando', '1', 4, 'Wonder Woman survives her battle against young god Ares only to discover her mother is missing-and so is Aphrodite\'s child! Together, they\'ll turn the world upside down to find them, but they must fight a pack of wayward Titans first. Can they convince Diana\'s foe Giganta to join the fight?', 169, 'assets/img/wonderwoman2.png', 0, 17, 'DC Comics', 'DC Comics', 'Wonder Woman'),
(6, 'Deadpool - Tome 2', 'Deadpool', 0, 'Rob Liefeld', '2008', '458516068', 0, 'Super-vilains', 'Fabian Nicieza', '1', 3, 'Dans le présent, Spider-Man doit supporter Deadpool. Dans le futur, Peter et Wade doivent affronter une horde de clones de Deadpool. Qui est le plus à plaindre ? Vous le découvrirez dans cinq épisodes riches en rebondissements, en découpages au katana et en copies de super-héros.', 112, 'assets/img/deadpool-volume-2.png', 0, 75, 'Marvel Panini France', 'Marvel', NULL),
(7, 'Batman: Three Jokers - Tome 1', 'Joker', 0, 'Jason Fabok', '26/08/2020', '9781779500243', 1, 'Super-vilains', 'Geoff Johns', '1', 4, 'Thirty years after Batman: The Killing Joke changed comics forever, Three Jokers reexamines the myth of who, or what, The Joker is and what is at the heart of his eternal battle with Batman. New York Times bestselling writer Geoff Johns and Jason Fabok, the writer/artist team that waged the “Darkseid War” in the pages of Justice League, reunite to tell the ultimate story of Batman and The Joker!', 210, 'assets/img/joker1.png', 0, 15, 'DC Comics', 'DC Comics', 'Three Jokers'),
(8, 'Clark Kent : Superman - Tome 3', 'Superman', 1, 'Ivan Reis', '07/02/2020', '9791026820604', 0, 'Super-héros', 'Brian Michael Bendis', '1', 3, 'Toujours bouleversés par les révélations de Rogol Zarr, véritable responsable de la destruction de Krypton, Superman et Supergirl continuent leur enquête sur ce dangereux extraterrestre. Mais Clark a également fort à faire avec son fils, Jon, revenu sur Terre avec quelques années de plus alors qu\'il n\'était parti avec son grand-père à travers l\'espace que quelques semaines auparavant... Et le récit de Jon concernant ce périple n\'est pas sans raviver en l\'Homme d\'Acier de nombreux doutes quant à Jor-El, ce père revenu d\'entre les morts.', 190, 'assets/img/superman3.png', 0, 27, 'Urban Comics', 'DC Comics', 'Clark Kent'),
(9, 'Batman: Three Jokers - Tome 3', 'Joker', 0, 'Jason Fabok', '28/10/2020', '9781779500243', 1, 'Super-vilains', 'Geoff Johns', '1', 5, 'The final chapter of the most terrifying and personal Batman mystery is here! Still reeling from their last encounter with the three Jokers, Batman, Batgirl, and Red Hood discover the terrible truth about the Three Jokers’ plot. Will the caped crusaders have the strength needed to put an end to the maniacal menaces’ master plan once and for all, or will it be lights out for good? You won’t want to miss the stunning conclusion of Batman: Three Jokers as it completes its trajectory as the ultimate examination of The Joker and his never-ending conflict with Batman', 300, 'assets/img/jokers3.png', 0, 30, 'DC Comics', NULL, 'Three Jokers'),
(10, 'Harley Quinn: Rebirth - Tome 3', 'Harley Quinn', 1, 'John Timms', '14/08/2018', '9793026819301', 0, 'Super-vilains', 'Jimmy Palmiotti', '1', 4, 'Maintenant qu\'elle n\'a plus à faire face à son clown psychotique favori, Harley Quinn peut enfin vivre une vie tranquille. Mais c\'était sans compter son ancienne rivale, Harley Sinn, qui a réussi à quitter les barreaux de sa prison et qui est bien décidée à prendre sa revanche. Et en parallèle, le maire de Coney Island met en place un plan pour se débarrasser des sans-abri, et ça risque de ne pas plaire à tout le monde. De quoi mettre Harley en rogne. Et croyez-moi, vous n\'avez pas envie de la voir dans cet état !', 152, 'assets/img/harley3.png', 0, 21, 'DC Comics Rebirth', 'DC Comics', 'Harley Quinn Rebirth'),
(11, 'Marvel Legacy', 'Marvel Legacy', 0, 'Esad Ribic', '01/06/2015', '9780785198658', 1, 'Super-héros', 'Jason Aaron', '1', 4, 'Le nouvel event de Marvel appelé marvel legacy!', 135, 'assets/img/Marvel_Legacy.png', 0, 65, 'Panini comics', 'Marvel', NULL),
(12, 'Marvel Icons Hors Série - Tome 17', 'Captain America', 0, 'Bryan Hitch', '10/06/2010', '9782809416060', 1, 'Super-héros', 'Ed Brubaker', '1', 4, 'Le Marvel Icons hors série 17 accueille la première partie de la mini-série Captain America : Reborn. Pour ceux qui ne seraient pas au courant, Steve Rogers, alias Captain America, est mort. Le héros a été tué, juste après Civil War, par Sharon Carter, alors sous l\'emprise de Crâne Rouge. Depuis, le bouclier a été repris par James Barnes, anciennement Winter Soldier et fidèle compagnon de route de Cap. Evidemment, en habitués des comics mainstrean et de leurs règles implicites, nous nous attendions à voir Rogers revenir d\'entre les morts un jour ou l\'autre. Marvel a tout de même réussi à patienter plus de deux ans avant de remettre le personnage sur le devant de la scène. Il faut dire que Barnes faisait un bien piètre remplaçant, bien moins charismatique en tout cas que son illustre prédécesseur.', 103, 'assets/img/Renaissance_1_2_Marvel_Icons_Hors_Serie_tome_17.png', 0, 50, 'Panini Comics', 'Marvel', 'Marvel icons Hors Série'),
(13, 'Docteur Strange: 100% Marvel - Tome 2', 'Docteur Strange', 0, 'Marcos Martin', '29/05/2008', '9782809402926', 0, 'Super-héros', 'Brian K. Vaughan', '1', 3, 'Le Docteur Strange mène l\'enquête la plus étrange de toute sa carrière. Il va tenter de résoudre l\'énigme d\'une tentative de meurtre... sur sa propre personne ! Avec son fidèle Wong, lui aussi à l\'article de la mort, Strange explore un lieu inattendu de l\'univers Marvel pour se trouver une nouvelle alliée...', 142, 'assets/img/docteur-strange-tome-2.png', 0, 80, 'Marvel', 'Marvel', 'Docteur Strange'),
(14, 'Captain Marvel And The Carol Corps', 'Captain Marvel', 0, 'David Lopez', '01/06/2015', '9780785198659', 1, 'Super-girl', 'kelly Sue DeConnick', '1', 4, 'Captain Marvel, qui en fait à le grade de Colonel, est décidée à découvrir ce qu’il y a de l’autre côté du ciel. L’escadron Banshee est prêt à la suivre partout, surtout droit vers la court martiale si cela se sait.', 112, 'assets/img/Captain_Marvel_And_The_Carol_Corps.png', 0, 120, 'marvel', 'Marvel', 'Captain Marvel'),
(15, 'Daredevil: 100 % Marvel - Tome 3', 'Daredevil', 0, 'Tim Sale', '12/01/2004', '9782845380912', 0, 'Anti-héros', 'Jeph Loeb', '1', 4, 'Avocat le jour, super héros la nuit, Matt Murdock possède une ouie, un odorat, une force et une agilité particulièrement développés. Et même s\'il est aveugle, son sens radar lui permet de se diriger et d\'éviter le moindre obstacle. Inlassablement, il arpente les rues de New-York à la poursuite de criminels en tout genre sous le nom de Dardevil, l\'homme sans peur.', 224, 'assets/img/daredevil-tome-3.png', 0, 62, 'Marvel', 'Marvel', 'Daredevil'),
(16, 'Batman: Joker War - Tome 2', 'Batman', 0, 'Guillem March, Tony Daniel, Jorge Jimenez', '26/02/2021', '9791026819332', 1, 'Super-vilains', 'James Tynion IV', '1', 4, 'Après avoir affronté le Designer, Batman réalise que son ennemi de toujours, le Joker, tirait en réalité les ficelles des événements récents. Le Clown prince du crime a, de son côté, trouvé une nouvelle compagne, Punchline, qui ne tarde pas à s\'opposer à son ancienne conquête, Harley Quinn ! La ville de Gotham sombre dans le chaos tandis la vie de Bruce Wayne, privé de sa fortune, se trouve à jamais bouleversée !', 100, 'assets/img/batman-joker-war_tome_2.png', 0, 20, 'Urban Comics', 'DC Comics', 'Joker War'),
(17, 'Harley Quinn, Tome 1', 'Harley Quinn', 0, 'Riley Rossmo', '21/03/2021', NULL, 1, 'Super-vilains', 'Stephanie Phillips', '3', 4, 'Harley Quinn revient à Gotham City pour compenser les péchés de son passé et aider la ville à se remettre de \'The Joker War\'.', 50, 'assets/img/Harley_Quinn.png', 0, 20, 'DC Comics', 'DC Comics', NULL),
(18, 'Daredevil: 100 % Marvel - Tome 11', 'Daredevil', 0, 'Alex Maleev', '13/07/2006', '9782845387447', 0, 'Anti-héros', 'Brian Michael Bendis', '1', 5, 'Celui qui était le Caïd avant Wilson Fisk refait surface? et veut la peau de Matt Murdock. Et qui a récupéré l\'amulette du Tigre Blanc ?', 204, 'assets/img/daredevil-tome-11.png', 0, 60, 'Panini Comics', 'Marvel', 'Daredevil'),
(19, 'Daredevil: 100 % Marvel - Tome 16', 'Daredevil', 0, 'Michael Lark', '15/04/2009', '9782809406788', 0, 'Anti-héros', 'Ed Brubaker', '1', 4, 'Matt Murdock doit faire face aux bouleversements de son existence et trouve enfin un moyen d\'aller de l\'avant. Mais une nouvelle menace surgie de son passé pointe à l\'horizon. Et après le désastre de la guerre civile, incarner Daredevil est devenu encore plus difficile.', 150, 'assets/img/daredevil-tome-16.png', 0, 58, 'Marvel Panini France', 'Marvel', 'Daredevil'),
(20, 'Clark Kent : Superman - Tome 1', 'Superman', 0, 'Ivan Reis', '26/04/2019', '9791026815716', 0, 'Super-héros', 'Brian Michael Bendis', '1', 2, 'Séparé de sa femme et de son fils, Superman tente tant bien que mal de maintenir sa double vie à flot. Un équilibre ténu qui vacille lorsque la Terre, sa planète d\'adoption, se retrouve projetée dans la Zone Fantôme, la prison interdimensionnelle créée sur Krypton, son monde natal, afin de maintenir en captivité les plus grandes menaces de l\'univers ! Secondé par une Ligue de Justice malheureusement dépassée, Superman va devoir trouver un moyen de ramener la Terre dans sa véritable dimension.', 155, 'assets/img/superman1.png', 0, 21, 'Urban Comics', 'DC Comics', 'Clark Kent'),
(21, 'Clark Kent : Superman - tome 5', 'Superman', 0, 'John Romita Jr', '05/02/2021', '9791026819820', 1, 'Super-héros', 'Brian Michel Bendis', '1', 4, 'Depuis que Superman a révélé son identité secrète, le chaos règne dans les rues de Metropolis... La mafia invisible, Lex Luthor et la Legion Fatale en ont fait leur terrain de jeu, et s\'y s\'affrontent pour en prendre le contrôle. De leur côté, les héros font leur possible pour protéger la ville, mais c\'est une guerre sans merci qui se prépare. Dans cette lutte, le plus grand des super-héros ne sera pas de trop, mais maintenant que tous connaissent le secret de l\'Homme d\'Acier, sera-t-il bien en mesure de défendre Metropolis ? Et ses proches sont-ils seulement en sécurité ?', 120, 'assets/img/apocalypse_a_metropolis_clark_kent_superman_tome_5.png', 0, 20, 'Urban Comics', 'DC Comics', 'Superman'),
(22, 'Clark Kent : Superman - tome 4', 'Superman', 1, 'Ivan Reis', '25/09/2020', '9791026817291', 1, 'Super-héros', 'Brian Michael Bendis', '2', 5, 'Pendant des années, Superman a défendu la justice, la vérité et l\'idéal humain tout en menant une vie tranquille de journaliste d\'un grand quotidien, le Daily Planet. Mais aujourd\'hui, l\'Homme d\'Acier a pris la plus grave décision de son existence : révéler au monde le secret de son identité secrète ! Comment ses plus proches alliés et surtout ses pires ennemis vont-ils réagir à ce qui devient rapidement le scoop du siècle ?', 180, 'assets/img/superman4.png', 0, 30, 'Urban Comics', 'DC Comics', 'Superman'),
(23, 'Clark Kent : Superman - Tome 2', 'Superman', 0, 'Ryan Sook', '05/07/2019', '9791026816362', 0, 'Super-héros', 'Brian Michael Bendis', '2', 5, 'Pendant longtemps, on s\'est demandé comment des criminels pouvaient évoluer dans les entrailles de Metropolis, la ville célèbre pour les exploits de son protecteur, Superman ! Aujourd\'hui, alors que le Daily Planet est sur le point de sombrer et que les incendies se multiplient en ville, l\'Homme d\'Acier découvre qu\'un ennemi invisible s\'insinue dans les quartiers les plus dangereux.', 182, 'assets/img/superman2.png', 1, 24, 'Urban Comics', 'DC Comics', 'Clark Kent'),
(24, 'Daredevil: 100 % Marvel - Tome 1', 'Daredevil', 0, 'Jimmy Palmiotti', '12/06/2020', '10254566068', 1, 'Anti-héros', 'Kevin Smith', '1', 5, 'Dans les premières pages signées par le réalisateur Kevin Smith, une adolescente affolée confie son bébé à Matt Murdock. Elle prétend que le nouveau-né est le sauveur de l\'humanité, l\'enfant du miracle. Mais un inconnu raconte à Murdock une histoire radicalement différente sur cet enfant. Tandis que Daredevil tente de démêler le vrai du faux, le redoutable Bullseye entre en lice, bien déterminé s\'emparer du bébé et à tuer le héros dans la foulée. Les fans comme la critique ont qualifié la prestation en huit volets de Smith comme l\'une des meilleures sagas jamais écrites pour Daredevil - une aventure pleine de coups de théâtre qui confronte l\'Homme sans Peur à la disparition tragique d\'un être cher.', 250, 'assets/img/daredevil-tome-1.png', 0, 73, 'Marvel Panini France', 'Marvel', 'Daredevil'),
(25, 'Batman & Robin: Integrale - Tome 3', 'Batman', 0, 'Patrick Gleason', '12/02/2021', '9791026817802', 1, 'Super-héros', 'Peter J. Tomasi', '1', 5, 'Bien que la mort de son fils unique, Damian, ait été l\'épreuve la plus douloureuse de sa carrière, Batman a su remonter la pente et trouver le courage d\'affronter les pires menaces de Gotham. Mais Ra\'s al Ghul ne l\'entend pas de cette oreille et tente par tous les moyens de ressusciter celui qui est également son petit-fils.', 100, 'assets/img/Batman_Robin_Integrale_Tome_3.png', 0, 20, 'Urban Comics', 'DC Comics', 'Batman & Robin'),
(26, 'Avengers Vs. Defenders: Marvel Classic - Tome 4', 'Avengers', 0, 'Bob Brown', '18/11/2011', '9782809422917', 1, 'Super-héros', 'Steve Englehart', '2', 4, 'Tirée des archives Marvel, vous allez assister à la bataille historique entre Vengeurs et Défenseurs, magistralement retranscrite par Steve Englehart, Bob Brown et Sal Buscema. Un classique du début des années 70 à ne pas manquer.', 144, 'assets/img/Avengers_Vs_Defenders_Marvel_Classic_tome_4.png', 0, 50, 'Marvel', 'Marvel', 'Marvel classic'),
(27, 'Batman Detective', 'Batman', 0, 'Tom Taylor', '13/04/2021', NULL, 1, 'Super-héros', 'Andy Kubert', '3', 4, 'Depuis que Superman a révélé son identité secrète, le chaos règne dans les rues de Metropolis... La mafia invisible, Lex Luthor et la Legion Fatale en ont fait leur terrain de jeu, et s\'y s\'affrontent pour en prendre le contrôle. De leur côté, les héros font leur possible pour protéger la ville, mais c\'est une guerre sans merci qui se prépare. Dans cette lutte, le plus grand des super-héros ne sera pas de trop, mais maintenant que tous connaissent le secret de l\'Homme d\'Acier, sera-t-il bien en mesure de défendre Metropolis ? Et ses proches sont-ils seulement en sécurité ?', 60, 'assets/img/Batman_The_Detective.png', 0, 20, 'DC Comics', 'DC Comics', 'Batman Detective'),
(28, 'Civil war 2: Captain Marvel - Tome 2', 'Captain Marvel', 0, 'Kris Anka', '14/02/2017', '9780785196433', 1, 'Super-girls', 'Ruth Fletcher', '1', 4, 'Captain Marvel Vol. 2: Civil War II - [Version Originale]', 103, 'assets/img/Civil_War_II_Captain_Marvel_2016_tome_2.png', 0, 15, 'Panini Comics', 'Marvel', 'Captain Marvel'),
(29, 'Teen Titans Academy', 'Teen Titans', 0, 'Tim Sheridan', '23/03/2021', NULL, 0, 'Super-héros', 'Rafa Sandoval', '2', 5, 'Bienvenue à la Teen Titans Academy! Rempli de nouveaux adolescents super puissants et de nombreux secrets sombres, le corps étudiant de Teen Titans Academy comprend Shazam; un nouveau speedster australien; un trio d\'expatriés adolescents gothiques obsédés par Batman - et un membre de cette première classe deviendra le mortel Red X.Les nouveaux Teen Titans originaux, dont Nightwing, Starfire, Raven, Cyborg et Beast Boy, jouent le rôle d\'enseignants et mentors pour adolescents surpuissants. Leur objectif: façonner la prochaine génération de héros', 100, 'assets/img/Teen_Titans_Academy.png', 1, 20, 'Urban Comics', 'DC Comics', 'Teen Titans Academy'),
(30, 'The Uncanny X-Men - Tome 5', 'X Men', 0, 'John Buscema', '11/07/2012', '9780785158721', 1, 'Super-héros', 'Chris Claremont', '1', 4, 'The X-Men had fought many battles, been on adventures that spanned galaxies, grappled with enemies of limitless might, but none of this could prepare them for the most shocking struggle they would ever face. Jean Grey has gained power beyond all comprehension, corrupting her and transforming her into the Dark Phoenix! Now they must decide is the life of the woman they cherish worth the existence of the entire universe! It\'s the definitive X-Men tale, painstakingly restored for the Marvel Masterworks.', 320, 'assets/img/Marvel_Masterworks_The_Uncanny_X_Men_Volume_5.png', 0, 65, 'Panini comics', 'Marvel', 'X-men'),
(31, 'Docteur Strange: le serment - Tome 103', 'Docteur Strange', 0, 'Marcos Martin', '01/02/2018', '9780785196433', 1, 'Super-héros', 'brian k. Vaughan', '1', 4, 'Ce volume rassemble les épisodes Doctor Strange: The Oath 1 à 5. L\'album, à couverture avec vernis sélectif et sans ISBN, porte le numéro 64 pour insertion dans la frise. Avec en fin d\'album, 3 pages d\'illustrations et 2 pages de Brain K. Vaughan et Marcos Martin qui évoquent le Serment.', 112, 'assets/img/Docteur_Strange_Le_Serment_Marvel_Comics_La_Collection_tome.png', 0, 25, 'Hachette', 'Marvel', 'Docteur Strange'),
(32, 'Iron Man - Tome 3', 'Iron Man', 0, 'Adi Granov', '10/05/2011', '9782809419931', 0, 'Super-héros', 'Warren Ellis', '1', 5, 'Tony Stark est confronté à un virus informatique d\'un nouveau genre... Est-ce le début d\'une révolution pour Iron man?', 284, 'assets/img/iron-man-tome-3.png', 0, 42, 'Marvel Panini France', 'Marvel', 'Iron Man'),
(33, 'Batman: Three Jokers - Tome 2', 'Joker', 0, 'Jason Fabok', '30/09/2020', '9782809492460', 1, 'Super-vilains', 'Geoff Johns', '2', 5, 'As Batman and Batgirl follow an unexpected thread linking the three Jokers with someone from the Dark Knight’s past, Red Hood dives headfirst into trouble and finds himself struggling to stay afloat without the aid of his allies.', 250, 'assets/img/jokers2.png', 0, 20, 'DC Comics', 'DC Comics', 'Three Jokers'),
(34, 'Les Origines de Marvel: Les Années 60', 'Hulk', 0, 'Esad Ribic', '29/06/2017', '9780785197258', 1, 'Super-héros', 'Jason Aaron', '1', 4, 'Le volume rassemble les épisodes US Fantastic Four 1, Tales to Astonish 27 et 44, Incredible Hulk 1, Amazing Fantasy 15, Tale of Suspense 39, Uncanny X-Men 1, Avengers 1 et 4, Daredevil 1.', 135, 'assets/img/Couv_306476.png', 0, 189, 'Panini comics', 'Marvel', NULL),
(35, 'Batman Death Metal - Tome 2', 'Batman', 0, 'Greg Capullo', '29/01/2021', '9791026819714', 0, 'Super-héros', 'James Tynion IV, Scott Snyder', '1', 3, 'Devenue maîtresse des enfers et gardienne des super-vilains opposants au Batman Qui Rit, Wonder Woman a fini par éliminer cet être diabolique et a rejoint ses alliés pour libérer la Terre et le Multivers du joug de Perpetua. Mais le Batman Qui Rit renaît de ses cendres sous une nouvelle forme, son cerveau transposé dans le corps d\'un Bruce Wayne surpuissant. Les résistants de la Ligue de Justice pourront-ils vaincre leur pire cauchemar : un Batman aux pouvoirs sans limites ?', 100, 'assets/img/Batman_Death_Metal_tome_2.png', 1, 20, 'Urban Comics', 'DC Comics', 'Batman Death Metal'),
(36, 'Harley Quinn: Rebirth - Tome 9', 'Harley Quinn', 0, 'John Timms', '09/08/2020', '9791026819301', 0, 'Super-vilains', 'Sam Humphries', '1', 5, 'Quand un médecin renommé de Gotham est retrouvé mort, la fameuse toxine du Joker dans les veines, tout semble désigné Harley Quinn comme première suspect... Mais celle-ci n\'y est pour rien, et pour prouver son innocence, elle va devoir s\'associer au plus grand détective qui soit : le Chevalier Noir. Une occasion en or pour la reine de Coney Island de réaliser un de ses plus grands rêves : devenir la sidekick de Batman – à moins que ce ne soit lui qui soit le sidekick de Harley Quinn... ?!', 188, 'assets/img/harley9.png', 1, 26, 'DC Comics Rebirth', 'DC Comics', 'Harley Quinn Rebirth'),
(37, 'Ultimate Spider-Man - Tome 10', 'Spiderman', 0, 'Mark Bagley', '15/06/2016', '9782809455526', 1, 'Super-héros', 'Brian Michael Bendis', '1', 5, 'Daredevil propose à Spider-Man de rejoindre le Docteur Strange, Iron Fist et Moon Knight pour vaincre le Caïd. C\'est le début des ennuis pour Peter Parker qui subit en plus le retour du Bouffon Vert, les aléas de santé de sa tante May et la colère de son ex, Kitty Pryde !', 288, 'assets/img/Mort_d_un_Bouffon_Ultimate_Spider_Man_Marvel_Deluxe_tome_10.png', 0, 32, 'Panini Comics', 'Marvel', 'Ultimate Spiderman'),
(38, 'Future State: Harley Quinn', 'Harley Quinn', 0, 'Stephanie Phillips', '12/01/2021', NULL, 0, 'Super-vilains', 'Simone DI Meo', '2', 5, NULL, 100, 'assets/img/Future_State_Harley_Quinn.png', 1, 20, 'Urban Comics', 'DC Comics', 'Future State'),
(39, 'Daredevil: 100 % Marvel - Tome 8', 'Daredevil', 0, 'Alex Maleev', '21/12/2004', '9782845384385', 0, 'Anti-héros', 'Brian Michael Bendis', '1', 4, 'Daredevil a bien des problèmes. Non seulement un journal a révélé sa véritable identité, mais il doit en prime faire face à la criminelle schizophrène Typhoid Mary. Sans compter que le caïd a refait surface, bien décidé à reconquérir son territoire avec l\'aide du Tireur !', 184, 'assets/img/daredevil-tome-8.png', 0, 75, 'Marvel France', 'Marvel', 'Daredevil'),
(40, 'Marvel Zombies : Battleworld', 'Marvel Zombies', 0, 'Sean Philips', '01/12/2015', '9780785198789', 1, 'Super-héros', 'Robert Kirkman', '1', 4, 'Le nouvel event de Marvel appelé marvel legacy!', 112, 'assets/img/Marvel_Zombies_Battleworld.png', 0, 40, 'Marvel', 'Marvel', NULL);

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` char(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `prenom` char(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` char(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `telephone` char(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mdp` varchar(1500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `adresse` char(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `code_postal` int(5) DEFAULT NULL,
  `ville` char(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cb_proprietaire` char(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cb_numero` char(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cb_date` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cb_cryptogramme` int(3) DEFAULT NULL,
  `civilite` char(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `nom`, `prenom`, `email`, `telephone`, `mdp`, `adresse`, `code_postal`, `ville`, `cb_proprietaire`, `cb_numero`, `cb_date`, `cb_cryptogramme`, `civilite`) VALUES
(11, 'rovere', 'alex', 'wormz91@hotmail.fr', '0616617229', '$2y$10$poUy7Gemy7J/ytJajE9lD.oy4qTbZe13QhOeFoc607OGYmjQ4MX7C', '50 AVENUE SERGENT GABRIEL JOURDAN', 83100, 'toulon', 'jean', '46589', '12/4562', 658, 'mr'),
(12, 'Pastore de vardo', 'Sacha', 'sachou3@gmail.com', '0610950604', '$2y$10$./2hkL8wVQNRKhHh6GWwoOq3b2J0DtYcCOqP6w1JTPbd4/bmU/lKa', 'Rue de la bastideferaqfareq', 63500, 'BERGONNE', NULL, NULL, NULL, NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
